/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/react-shared-components/dist/**/*.js',
  ],
  safelist: [
    // Safelist all the classes your library uses
    'bg-blue-500',
    'bg-blue-600', 
    'bg-blue-700',
    'bg-gray-200',
    'bg-gray-300',
    'bg-red-500',
    'bg-red-600',
    'focus:ring-blue-500', 'disabled:bg-gray-400',
    'hover:bg-blue-600',
    'bg-transparent',
    'hover:bg-primary-600',
    'hover:bg-gray-300',
    'hover:bg-red-600',
    'hover:bg-gray-100',
    'text-white',
    'text-gray-900',
    'text-gray-700',
    'text-red-500',
    'hover:text-gray-700',
    'border',
    'border-gray-200',
    'border-red-200',
    'border-green-200',
    'border-blue-200',
    'border-b',
    'border-gray-100',
    'rounded-lg',
    'rounded-xl',
    'shadow-sm',
    'shadow-md',
    'shadow-xl',
    'p-3',
    'p-4',
    'p-6',
    'p-8',
    'pb-4',
    'px-3',
    'px-4',
    'px-6',
    'py-1.5',
    'py-2',
    'py-3',
    'm-8',
    'mb-4',
    'mb-6',
    'mt-6',
    'mt-8',
    'flex',
    'inline-flex',
    'items-center',
    'justify-center',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'transition-all',
    'duration-200',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-primary-500',
    'focus:ring-gray-500',
    'focus:ring-red-500',
    'disabled:bg-gray-400',
    'disabled:bg-gray-100',
    'disabled:text-gray-400',
    'min-h-screen',
    'bg-gray-50',
    'bg-gray-900',
    'bg-white',
    'max-w-4xl',
    'mx-auto',
    'space-y-4',
    'space-x-2',
    'gap-2',
    'gap-4',
    'gap-6',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'lg:grid-cols-3',
    'overflow-hidden',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        }
      },
    },
  },
  plugins: [],
}